# Generated by Django 5.1.7 on 2025-03-31 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaDeInicio', models.CharField(auto_created=True, help_text='fecha a iniciar', max_length=100)),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Modificado', models.DateTimeField(auto_now=True)),
                ('Status', models.BooleanField(default=True)),
                ('pk_publica', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Codigo', models.CharField(blank=True, max_length=60, null=True)),
                ('Nombre', models.CharField(help_text='Nombre del Proyecto', max_length=100)),
                ('Descripcion', models.CharField(default='', help_text='Descripcion del proyecto', max_length=500, null=True)),
                ('AlertaDiaria', models.BooleanField(default=False)),
                ('AlertaSemanal', models.BooleanField(default=False)),
                ('TormentaDeAlerta', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userproyecto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='emailreportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Modificado', models.DateTimeField(auto_now=True)),
                ('Status', models.BooleanField(default=True)),
                ('pk_publica', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Codigo', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(default='', max_length=100)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emailreportes', to='proyecto.proyecto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
