# Generated by Django 5.1.7 on 2025-04-01 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='user',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado'), ('En progreso', 'En progreso'), ('Cancelado', 'Cancelado')], default='En progreso', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='FechaDeFin',
            field=models.CharField(default='', help_text='fecha a iniciar', max_length=100),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='asignados',
            field=models.ManyToManyField(default=None, null=True, related_name='asignaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userproyecto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='FechaDeInicio',
            field=models.CharField(default='', help_text='fecha a iniciar', max_length=100),
        ),
    ]
