# Generated by Django 5.1.7 on 2025-04-02 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_tarea_comentario'),
        ('user', '0004_rename_user_contacto_to_user_contacto_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentariotarea', to='user.contacto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='asignados',
            field=models.ManyToManyField(default=None, related_name='asignaciones', to='user.contacto'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='Usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareauser', to='user.contacto'),
        ),
    ]
