# Generated by Django 5.1.7 on 2025-04-02 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_alter_comentario_usuario_alter_proyecto_asignados_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='Usuario',
            new_name='contacto',
        ),
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectotarea', to='proyecto.proyecto'),
        ),
    ]
