# Generated by Django 5.1.7 on 2025-04-02 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_rename_usuario_tarea_contacto_tarea_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='Fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 11, 38, 39, 760528)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='FechaDeFin',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 11, 38, 39, 759008), help_text='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='FechaDeInicio',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 11, 38, 39, 758009), help_text='fecha a iniciar'),
        ),
    ]
