# Generated by Django 5.1.7 on 2025-04-02 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_tarea_fecha_vencimiento_alter_proyecto_fechadefin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='contacto',
            new_name='asignado',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='FechaDeFin',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 12, 53, 49, 440991), help_text='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='FechaDeInicio',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 12, 53, 49, 440991), help_text='fecha a iniciar'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='Fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 12, 53, 49, 441991)),
        ),
    ]
