# Generated by Django 5.1.7 on 2025-04-02 19:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_rename_contacto_tarea_asignado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentariotarea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='FechaDeFin',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 15, 39, 10, 630912), help_text='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='FechaDeInicio',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 15, 39, 10, 630912), help_text='fecha a iniciar'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='Fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 15, 39, 10, 631915)),
        ),
    ]
