# Generated by Django 5.1.7 on 2025-04-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_roles_Default'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userPartial',
        ),
    ]
