# Generated by Django 5.1.7 on 2025-04-02 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_userpartial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='user',
            new_name='to_user',
        ),
        migrations.AddField(
            model_name='contacto',
            name='ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referenciacontacto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Correo',
            field=models.CharField(max_length=50),
        ),
    ]
